// Collection de peliculas
const Movies = [
  {
    name: "Iron Man",
    description: "",
    gender: "",
    duration: "",
    year: 2008,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "El increíble Hulk",
    description: "",
    gender: "",
    duration: "",
    year: 2008,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Iron Man 2",
    description: "",
    gender: "",
    duration: "",
    year: 2010,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Thor",
    description: "",
    gender: "",
    duration: "",
    year: 2011,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Capitán América: El primer vengador",
    description: "",
    gender: "",
    duration: "",
    year: 2011,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Los Vengadores",
    description: "",
    gender: "",
    duration: "",
    year: 2012,
    rate: "",
    imageUrl:
      "https://es.web.img3.acsta.net/pictures/14/03/10/10/35/587504.jpg",
    trailerUrl: "",
  },
  {
    name: "Iron Man 3",
    description: "",
    gender: "",
    duration: "",
    year: 2013,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Thor: El mundo oscuro",
    description: "",
    gender: "",
    duration: "",
    year: 2013,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Capitán América: El soldado de invierno",
    description: "",
    gender: "",
    duration: "",
    year: 2014,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Guardianes de la Galaxia",
    description: "",
    gender: "",
    duration: "",
    year: 2014,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Vengadores: La era de Ultrón",
    description: "",
    gender: "",
    duration: "",
    year: 2015,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Ant-Man",
    description: "",
    gender: "",
    duration: "",
    year: 2015,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Capitán América: Civil War",
    description: "",
    gender: "",
    duration: "",
    year: 2016,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Doctor Strange",
    description: "",
    gender: "",
    duration: "",
    year: 2016,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Guardianes de la Galaxia Vol. 2",
    description: "",
    gender: "",
    duration: "",
    year: 2017,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Spider-Man: Homecoming",
    description: "",
    gender: "",
    duration: "",
    year: 2017,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Thor: Ragnarok",
    description: "",
    gender: "",
    duration: "",
    year: 2017,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Black Panther",
    description: "",
    gender: "",
    duration: "",
    year: 2018,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Vengadores: Infinity War",
    description: "",
    gender: "",
    duration: "",
    year: 2018,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Ant-Man y la Avispa",
    description: "",
    gender: "",
    duration: "",
    year: 2018,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Capitana Marvel",
    description: "",
    gender: "",
    duration: "",
    year: 2019,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
  {
    name: "Vengadores: Endgame",
    description: "",
    gender: "",
    duration: "",
    year: 2019,
    rate: "",
    imageUrl: "https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SY679_.jpg",
    trailerUrl: "",
  },
  {
    name: "Spider-Man: Lejos de casa",
    description: "",
    gender: "",
    duration: "",
    year: 2019,
    rate: "",
    imageUrl: "",
    trailerUrl: "",
  },
];
export default Movies;
