export const types = {
  login: "[Auth] Login ",
  logout: "[Auth] Logout",
  signup: "[Auth] Sign Up",
  bannerList: "[Banner] List",
  bannerCreate: "[Banner] Create",
  movieList: "[Movies] List",
  movie: "[Movie] Current",
  movieCreate: "[Movie] Create",
  movieEdit: "[Movie] Edit",
  moviesTop: "[Movie] Top",
  moviesLeast: "[Movie] Least",
  uiSetError: "[UI] Set Error",
  uiRemoveError: "[UI] Remove Error",
  uiStartLoading: "[UI] Start Loading",
  uiFinishLoading: "[UI] Finish Loading",
};
